
spring:
  application:
    name: api-gateway

server:
  port: 8080

zuul:
  sensitiveHeaders: Cookie, Set-Cookie


logging:
  level:
    org.springframework:
      web: DEBUG
      security: DEBUG





